- .travis.yml
- README.md
* Configure repo to use `ciena-devops` scripts
> Configure repo to use ciena-devops scripts

- .THROWAWAY
> Testing patch release

- .THROWAWAY
* Updated `broccoli-funnel` to `^2.0.1`
* Didn't really do any of that
> Another test

- .THROWAWAY
> Another attempt

- .THROWAWAY
> one more time

- .THROWAWAY
> might be the one

- .travis.yml
> Trying global install of semver

- .travis.yml
> Remove semver from global npm install in .travis.yml

- .THROWAWAY
- .gitignore
- package-lock.json
* **Upgraded** to `ember-test-utils@4.x`
* **Upgraded** to `ember-cli-code-coverage@0.3.12` (using a pinned `ember-code-snippet@1.7.0` so as to avoid overwriting `require` and breaking `ember-cli-code-coverage`)
* **Enabled** code coverage gating in PRs. 
* **Added** `onToggle` callback which is called with the new value whenever toggled
* **Deprecated** `onClick` callback, which wasn't handling raw functions very well when going through the event proxy
* **Fixed** [#439](https://github.com/ciena-frost/ember-frost-core/issues/439) Properly handle falsy `trueValue`/`falseValue` when `trueLabel`/`falseLabel` are set
> Minor release

- .THROWAWAY
> MAJOR release test

- .THROWAWAY
> Testing none release

- .travis.yml
* Use `^1.0.0` release of `ciena-devops`
> Use ^1.0.0 release of ciena-devops

- .THROWAWAY
> test mINOR

- .THROWAWAY
> Testing minor

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Testing none pr

- .github/PULL_REQUEST_TEMPLATE.md
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Change markdown syntax

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> patch pr test

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing minor pr

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing major pr

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Testing version checking

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Use published ciena-devops packager rather than branch

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Testing slack script changes

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Reverting back to released package version

- .THROWAWAY
No
n/a
n/a
Examples:
* **NONE**
* **PATCH**
* nothing about the outcome of the code has changed (though it likely corrected it)
* changes to demo app (_/tests/dummy/_)
* **MINOR**
* adding functionality in a backwards-compatible manner
* nothing about how used to use the code has changed but using it in a new way will do new things
* nothing about the outcome of the code has changed without having to first use it in a new …
> Testing protected branch protections with pr-bumper

- .github/CODEOWNERS
No
n/a
Examples:
* **NONE**
* **PATCH**
* nothing about the outcome of the code has changed (though it likely corrected it)
* changes to demo app (_/tests/dummy/_)
* **MINOR**
* adding functionality in a backwards-compatible manner
* nothing about how used to use the code has changed but using it in a new way will do new things
* nothing …
> Add .github/CODEOWNERS file

- .github/CODEOWNERS
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Update .github/CODEOWNERS file

- .github/CODEOWNERS
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Additional tweak

- .github/CODEOWNERS
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Removing teams

- .github/CODEOWNERS
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Add teams back after direction from GitHub support staff

- .THROWAWAY
- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing travis repo variables

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing travis env vars

- .THROWAWAY
- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> try setting  variable

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> update travis node version in travis.yml to be inline with rest of repos

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing PR from fork to upstream pre-release branch

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing upstream pre-release from PR causes new GitHub release

- .THROWAWAY
- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> testing the regular PR process

- .THROWAWAY
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Testing a PR from the creation of an upstream greenkeeper branch

- .travis.yml
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Configure greenkeeper-lockfile in .travis.yml

- package-lock.json
- package.json
* Closes #
Examples:
* **NONE**
* **PATCH** …
> added pr-bumper to list of dependencies

- package-lock.json
- package.json
* Closes #
Examples:
* **NONE**
* **PATCH** …
> Remove pr-bumper as a testing package
